on:
  push:
    branches: [ "github_action_test" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - run: pip install -r requirements.txt
    - run: python build.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
